NASA-AMMOS/AIT-GUI

bliss/gui/__init__.py
bliss/gui/static/js/bliss/format.js
bliss/gui/static/js/bliss/gui/Clock.js
bliss/gui/static/test/test_clock.js

The clock component now displays GPS time by default and supports
toggling between GPS, UTC, and UTC local time.
Resolve #3

Issue #3 - Add GPS time display to clock component

---

bliss/gui/bin/bliss_example.py
bliss/gui/static/index.html

Update the default `index.html` layout to include more organized telemetry points and plots. Add an example bin script for dumping packets with marching integers to the UI for demoing.
Resolve #1 
Resolve #2

Issue #1 and #2 - Add better default GUI examples

---

doc/source/conf.py
readthedocs.yml
setup.py

Resolves #10 
Preview of docs can be seen here: http://ait-gui.readthedocs.io/en/issue-10/

Issue #10 - Publish AIT GUI docs to ReadTheDocs

---

bliss/gui/static/js/bliss/gui/Messages.js

The format.datetime call in Messages has been updated so that UTC
display format is explicitly stated. Note, this should be updated in the
future to mirror message display in the same format that the Clock
component is using for consistency.

Issue #17 - Update Messages datetime format call to use UTC time

---

README.rst

Resolve #43 
I've transferred the contributing guidelines to the [wiki](https://github.com/NASA-AMMOS/AIT-Core/wiki/Contributing) and updated the contents to be repo agnostic. Let me know if you think we need to change some stuff on there.

Issue #43 - Update README with default contributing/community info

---

ait/gui/static/js/ait/gui/Status.js
ait/gui/static/js/ait/gui/TabSet.js

Cleanup the Tabset and LED docstrings so the formatting works properly and/or is cleaner. Switched out some Markdown inline code notation for bolded text.
Resolve #73

Issue #73 - Component docstring cleanup

---

ait/gui/__init__.py

Add optional data archiving support. Users can enable data archiving via
ait.gui.enable_data_archiving() prior to calling ait.gui.wait(). By
default InfluxDB will be used but an optional argument can be set when
calling enable_data_archiving() to choose a different class.
Update greenlet handling for monitoring and data archive tasks so that
exits via Ctrl-C are cleaner. Greenlet functions are now wrapped in
gevent.util.wrap_errors so that KeyboardInterrupt exceptions are
returned instead of raised. This allows us to avoid stack traces being
printed when killing the GUI.
Greenlet tracking has been changed from individual global variables to a
list of greenlet instances. Clean up code has been updated with this
change as well.
The ait.gui.wait function has been updated to use …

Issue #79 and #80 - Data archiving and better interrupt handling

---

ait/gui/static/js/ait/cmd.js
ait/gui/static/test/test_cmd.js

Commands are added to a default subsystem group on the frontend
during command dictionary parsing so that components that expect
commands to be grouped as such function as expected. Specifically, this
allows the CommandSearch object to get commands grouped as expected for
display. Since the subsystem attribute isn't required this means that the
CommandSearch component will default to all commands showing up under
this default subsystem header instead of not at all.
Resolve #82

Issue #82 - Add commands without subsystem to default subsystem group

---

ait/gui/static/js/ait/dtype.js
ait/gui/static/js/ait/evr.js
ait/gui/static/js/ait/gui/Field.js
ait/gui/static/test/test_evr.js

Update EVRDefinition to support optional 'message' attribute that is
currently supported in Core. The message attribute is a string that can
contain printf format strings that can be processed via
EVRDefinition.formatMessage().
Add EVRDefinition.formatMessage() for formatting an EVR's message
attribute with an array of data values. Most commonly this would be used
to format an EVR's info message with info returned in H&S data to
provide additional information to operators.
Fix typo in Field oninit where this._cached.rawval was being defaulted
to null instead of this._cached.val which is used throughout the code.
Update Field.oncreate so that popover content generation is handled in a
separate function (createPopoverContent) so that we can inherit from
Field for more customized displays. …

Issue #85 - Add support for EVR message formatting

---

ait/gui/static/js/ait/format.js
ait/gui/static/js/ait/gui/Clock.js
ait/gui/static/package-lock.json
ait/gui/static/package.json
ait/gui/static/test/test_clock.js

- added variable 'local' to Clock
- updated toggleTimeFormat to use new 'local' var
- updated function tz in format.js to return 'Local Time' string
- updated test_clock.js to test toggling between local time
- added fsevents 1.2.4 to package.json
Resolves #94

Issue #94 - Clock format toggling doesn't rotate through options as expected

---

ait/gui/__init__.py
ait/gui/openmct_adapter/ait_integration.js
ait/gui/openmct_adapter/example_ait_telem_fetch.js

Adds example OpenMCT component code for integrating AIT telemetry. The example components are implemented inline with the examples laid out in the OpenMCT tutorial. For more information, check the header in `ait_integration.js`.
Resolve #88

Issue #88 - Add support for integration with OpenMCT

---

ait/gui/static/css/ait/gui/Field.css
ait/gui/static/index.html
ait/gui/static/js/ait/gui/Field.js

Added `display_name` attribute to `ait-field` tag which `Field.view()` uses to return the following dom structure:
```
<ait-field> 
<name>[display_name: ]</name>
<value>[value]</field>
</ait-field>
```
Added css class for making `name` bold.
Resolves #61

Issue #61 - Adding tool tip to fieldname

---

ait/gui/__init__.py
test_scripts/notification_test.py

Resolves #92 
Eventually this should probably be a configurable parameter

Issue #92: Update monitoring with notification throttling

---

ait/gui/__init__.py

Instead of defaulting to port 8080, the ait gui should now look at the
ait config and pull the defined gui.port number from there if its defined.
If it is not defined, then it will use the default of 8080. All of which
gets overwritten if the user provided a port number to the init method

Issue #110 - Made GUI port optionally configurable

---

ait/gui/__init__.py
ait/gui/static/js/ait/gui/Playback.js

Update the server endpoints and Playback component so they fail gracefully when a database connection cannot be made.
Resolve #126

Issue #126 - Gracefully fail when database connection can't be made for playback

---

ait/gui/__init__.py
ait/gui/static/js/ait/gui/Playback.js

Previously, failure to connect to the specified datastore crashed the GUI plugin. 
Now, on a failed datastore connection the playback functionality will not work but the rest of the GUI will continue to run.

Issue #129 - Add error handling for playback module datastore connection

---

ait/gui/static/index.html

Issue #123 - Add 'user guide' to example index file

---

ait/gui/__init__.py

#142 should be merged first. This branch has been rebased with changes in #142.
To test this fix works, check out this branch and follow steps 2-4 outlined in #143 .
Resolves #143

Make end time match expected format (#143)

---

doc/source/conf.py
readthedocs.yml
setup.py

- Update Python version in RTD config
- Bump Sphinx version in GUI to match Core
- Fix gevent monkey patch timing issue (See NASA-AMMOS/AIT-Core#253 for additional info) by patching in GUI first thing in Sphinx conf.py. This might not be the final solution to this but it resolves issues for now.

Issue #156 - Update RTD Python version and fix doc build issues

---

ait/gui/__init__.py
ait/gui/static/index.html
ait/gui/static/js/ait/gui/Field.js
ait/gui/static/js/ait/gui/Plot.js
ait/gui/static/js/ait/gui/Search.js
ait/gui/static/js/ait/gui/index.js
ait/gui/static/js/ait/tlm.js
ait/gui/static/js/ait/util.js
test_scripts/notification_test.py

* Updated dict.iteritems to dict.items (#169)
* Added dntoeu plot option
* Added getPacket utility method

Issue #105_kkallas - Rework of Backend/Frontend telemetry processing

---

ait/gui/static/js/ait/gui/Field.js
ait/gui/static/js/ait/gui/index.js
ait/gui/static/js/ait/tlm.js

Field formatting now pulls a given fields packet definition from the
global ait.tlm.dict object instead of the "packet" being processed. The
packet passed around on message receipt was changed when the
front/backend exchange format was updated. The format handling
subsection was attempting to access the packet definition information
using the old format.
Drop a number of unneeded console.logs throughout.
Resolve #185 
Resolve #179

Issue #185 - Fix broken field formatting

---

ait/gui/__init__.py
ait/gui/static/js/ait/dtype.js
ait/gui/static/js/ait/gui/Field.js

Update handling of packet diffing to include complex types (Time, Cmd,
and EVR) in with DN-to-EU values. This pushes human-readable info for
these types to the frontend so clients don't need to inspect the
dictionaries to determine what should be displayed.
Update calls to `replace_datetimes` so the "dntoeu" diffs are passed
instead of the raw ones. Previously these calls weren't doing anything
since the passed diffs were always raw values. This was likely left in
from a previous iteration on this functionality.
Note, this doesn't make sweeping changes to the diffing code and instead
works around the existing framework. The current stuff is a bit of a
mess and could really use some TLC. We'll need to revisit this in a
follow up ticket.
Update the handling of Field format calls to fix …

Issue #189 - Update diff handling of complex types and human readable values

---

ait/gui/__init__.py

Packet diff handling when previously unseen packet was received failed
to properly initialized the `dntoeu` values for that packet. This meant
that UI clients would be unable to view the "human readable" versions of
fields in the GUI for any field that updated infrequently. This updates
the new packet type handling to properly update the `dntoeu` values as
well.
Resolve #194

Issue #194 - Fix improperly initialized 'dntoeu' packet states

---

ait/gui/__init__.py

Update the process_log_msg() helper to properly decode the received 0MQ
message from bytes into a str prior to passing it off to
log.parseSyslog. This necessary change was overlooked in our testing for
the new 0MQ send / recv call updates in Core / GUI.
Resolve #200

Issue #200 - Properly decode received log messages in GUI plugin

---

ait/gui/__init__.py

The original function name does not exist in the AIT core log module and looks to be a typo.
This causes an immediate error when using AIT-GUI.  
Changed the line to use the call in AIT core.
The error no longer appears.

Fix typo that makes call to log method that doesn't exist

---

ait/gui/static/js/ait/gui/Command.js

This PR adds the ability for users to view command argument information by clicking on the info icon. 
Examples: 
- **SEND_STR_ARG**
```
- !Command
name:      SEND_STR_ARG
opcode:    0x0005
subsystem: CMD
title: Send string argument value
desc:      |
This command tests sending a single string argument.
arguments:
- !Argument
name: str_arg
desc: String Argument
units: none
type: S16
bytes: [0,15]
```
- **SEQ_ENABLE_DISABLE**
```
- !Command
name:      SEQ_ENABLE_DISABLE
opcode:    0x0003
subsystem: CMD
title: Enable/Disable Sequence
desc:      |
This command enables or disabled the specified sequence.  If a
sequence to be disabled is currently executing, it will be
interrupted.
arguments:
- !Argument
name:  sequence_id
desc:  Sequence ID
units: none
type:  MSB_U16
bytes: [0,1]
- !Argument …
```

Issue #121 - Add help text popover for command arguments

---

ait/gui/static/js/ait/gui/TabSet.js

Issue #62 - Add badge to show total number of fields that are out of limit in a tab

---

README.rst

Add RTD docs build badge to the top of the README.
Resolve #243

Issue #243 - Add RTD build status badge to README

---

poetry.lock
pyproject.toml

Add greenlet dependency and pin to 1.1.3 for consistency with Core
`master` work. Note, poetry will report that the lock file is out of
date with these changes. That cant be updated until a Core tag is added
with the greenlet version changed which GUI and depend on.
Resolve #247

Issue #247 - Pin greenlet version
