NASA-AMMOS/AIT-GUI

- bliss/gui/static/js/bliss/gui/Search.js
> Issue #6 - Fix membership check in search limit formatting

- bliss/gui/static/js/bliss/format.js
> Issue #7 - Fix missing default UTC option in format helpers

- doc/source/index.rst
> Issue #14 - Update index.rst of docs

- bliss/gui/__init__.py
- bliss/gui/static/js/bliss/gui/Script.js
Add logic to /script/run to prevent execution of a script unless the
global greenlet object for script execution is None. Cleanup when the
debugger finishes running our scripts now resets this state. This should
ensure that no matter what we only have 1 script executing at a time.
Add logic to the ScriptExecCtrls to track execution logic in addition to
the global script execution information to ensure that button controls
aren't functioning in an undefined area between "button has been clicked
to execute script" and "events indicating script is running have
propagated". This prevents duplicate script execution due to quick
double clicks on the script execute button.
Resolve #20
> Issue #20 - Fix duplicate script execution

- bliss/gui/__init__.py
Add `enable_monitoring` GUI function for toggling on telemetry limit
monitoring via project's GUI initialization script. This Greenlet
monitors all inbound telemetry that the GUI receives via a Session and
sends limit notification triggers to the notification API when limit
trips occur.
Resolve #22
> Issue #22 - Add telemetry limit monitoring and user notification support

- .travis.yml
> Issue #28 - Setup Travis CI build

- CHANGELOG.md
> Issue #40 - Fix missing CHANGELOG releases

- ait/gui/static/package-lock.json
- ait/gui/static/package.json
> Issue #68 - Update Sinon package version so npm ci works

- ait/gui/static/js/ait/gui/Clock.js
- ait/gui/static/js/ait/gui/Command.js
- ait/gui/static/js/ait/gui/Field.js
- ait/gui/static/js/ait/gui/Messages.js
- ait/gui/static/js/ait/gui/Plot.js
- ait/gui/static/js/ait/gui/Query.js
- ait/gui/static/js/ait/gui/Script.js
- ait/gui/static/js/ait/gui/Search.js
- ait/gui/static/js/ait/gui/Sequence.js
- ait/gui/static/js/ait/gui/Status.js
- ait/gui/static/js/ait/gui/Util.js
- doc/source/conf.py
- doc/source/index.rst
- doc/source/widgets.rst
- readthedocs.yml
- setup.py
> Issue #47 - Add GUI widget docs

- ait/gui/__init__.py
Fix greenlet exception raising bug and add timestamp to out of limit notifications.
Resolve #76 
Resolve #78
> Issue #76 - Remove greenlet exception raise bug in limit monitoring

- ait/gui/__init__.py
> Issue #84 - Fix greenlet exception raise bug in telem monitoring code

- ait/gui/__init__.py
- ait/gui/static/js/ait/gui/Field.js
> Issue #90: EVR handling for limit monitoring

- ait/gui/static/js/ait/gui/Plot.js
> Issue #72 - Adding try/catch for errors in parsing plot config element

- ait/gui/__init__.py
Removed the call to the old way of defining the gui telemetry stream
> Issue #109 - Removed call to old config get method

- ait/gui/static/js/ait/gui/Plot.js
> Issue #131 - Add plot-range documentation to Plot component

- ait/gui/__init__.py
> Issue #133 - Fix typos on port and host parameter sets

- ait/gui/__init__.py
> Issue #135 - Default plugins to empty list if missing from config

- doc/source/new_project.rst
> Issue #49 - Fix config and server bootup documentation examples

- ait/gui/__init__.py
Update reference to DataArchive plugin.
Resolves #142.
> Issue #142 - Update references to AIT-Core plugins and handlers

- ait/gui/__init__.py
- setup.py
Implemented python 3.7 support:
c049679 Updated urllib.unquote to urllib.parse.unquote
d424c8e Decode command name bytes before running json dumps
ae9d351 Added eval to transform incoming tlm msg from byte string to actual bytes
ca8f1d3 Fixed pickle import and print statements
> Issue #145 - Implement python 3 support

- setup.py
Updated core version requirement for py3 support
> Issue #153 - Update core version requirement

- ait/gui/__init__.py
- ait/gui/static/js/ait/gui/Playback.js
Merge issues #143 and #142 first. 
Resolves #128
> Issue #128 - Request playback range from backend every minute

- ait/gui/__init__.py
Following items were updated:
* DataArchive location
* dict.has_key() was removed in python3. 'keyname' in dictionary was used.
* There was timestamp format inconsistencies between ait-tlm-db-insert and telemetry run commands. Proposed solution was updated.
> Issue #162 - Playback plugin update

- ait/gui/__init__.py
Resolve #164 
This is dependent upon the changes in NASA-AMMOS/AIT-Core#282.
> Issue #164 - Update CmdAPI instantiation to match Core API changes

- .gitignore
- MANIFEST.in
- ait/gui/static/package-lock.json
Minor updates to issues noticed during the 2.0 release.
- Update package-lock.json with the latest version
- Update MANIFEST.in to avoid picking up node_modules
- Update .gitignore to ignore dist/ folder
Resolve #167
> Issue #167 - Post release cleanup

- ait/gui/static/js/ait/gui/index.js
* Changed the handler to trigger `m.redraw()` every second.
> Issue #173 - Update GUI refresh handler

- ait/gui/__init__.py
Add derived telemetry values:
- Append (update) derivations dict to raw dict
Resolve #171
> Issue #171 - Add derived telemetry values

- ait/gui/__init__.py
> Issue #183 - Minor typo fix in static directory warn

- ait/gui/static/js/ait/gui/Search.js
Fix getFieldType call typo in the Search component.
Resolve #187
> Issue #187 - Fix broken Search component

- ait/gui/__init__.py
> Issue #192 - Update Plugin data handling to match Core changes
